//! TypeScript 代码生成器
//! 
//! 将 Thrift AST 转换为 TypeScript 类型定义

use crate::ast::*;
use std::fmt::Write;

/// TypeScript 代码生成器
pub struct TypeScriptGenerator {
    /// 生成的代码
    output: String,
    /// 缩进级别
    indent_level: usize,
    /// 是否生成只读类型
    pub readonly: bool,
    /// 是否生成导出声明
    pub export: bool,
}

impl TypeScriptGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            readonly: false,
            export: true,
        }
    }
    
    /// 获取当前缩进字符串
    fn indent(&self) -> String {
        "  ".repeat(self.indent_level)
    }
    
    /// 写入一行
    fn write_line(&mut self, line: &str) {
        let _ = writeln!(self.output, "{}{}", self.indent(), line);
    }
    
    /// 写入空行
    fn write_empty_line(&mut self) {
        let _ = writeln!(self.output);
    }
    
    /// 生成整个文档
    pub fn generate(&mut self, doc: &ThriftDocument) -> String {
        self.output.clear();
        
        // 生成文件头注释
        self.write_line("// This file is auto-generated by thrift-to-ts");
        self.write_line("// Do not edit manually");
        self.write_empty_line();
        
        // 生成常量
        for constant in &doc.constants {
            self.generate_constant(constant);
            self.write_empty_line();
        }
        
        // 生成类型别名 (typedef)
        for typedef in &doc.typedefs {
            self.generate_typedef(typedef);
            self.write_empty_line();
        }
        
        // 生成枚举
        for enum_def in &doc.enums {
            self.generate_enum(enum_def);
            self.write_empty_line();
        }
        
        // 生成结构体
        for struct_def in &doc.structs {
            self.generate_struct(struct_def);
            self.write_empty_line();
        }
        
        // 生成 Union
        for union_def in &doc.unions {
            self.generate_union(union_def);
            self.write_empty_line();
        }
        
        // 生成异常
        for exception in &doc.exceptions {
            self.generate_exception(exception);
            self.write_empty_line();
        }
        
        // 生成服务接口
        for service in &doc.services {
            self.generate_service(service);
            self.write_empty_line();
        }
        
        self.output.trim_end().to_string() + "\n"
    }
    
    /// 生成常量
    fn generate_constant(&mut self, constant: &Constant) {
        let export = if self.export { "export " } else { "" };
        let ts_type = self.field_type_to_ts(&constant.field_type);
        let value = self.const_value_to_ts(&constant.value);
        
        self.write_line(&format!(
            "{}const {}: {} = {};",
            export, constant.name, ts_type, value
        ));
    }
    
    /// 生成类型别名
    fn generate_typedef(&mut self, typedef: &Typedef) {
        let export = if self.export { "export " } else { "" };
        let ts_type = self.field_type_to_ts(&typedef.original_type);
        
        self.write_line(&format!(
            "{}type {} = {};",
            export, typedef.alias, ts_type
        ));
    }
    
    /// 生成枚举
    fn generate_enum(&mut self, enum_def: &Enum) {
        let export = if self.export { "export " } else { "" };
        
        self.write_line(&format!("{}enum {} {{", export, enum_def.name));
        self.indent_level += 1;
        
        for (i, value) in enum_def.values.iter().enumerate() {
            let comma = if i < enum_def.values.len() - 1 { "," } else { "" };
            
            if let Some(v) = value.value {
                self.write_line(&format!("{} = {}{}", value.name, v, comma));
            } else {
                self.write_line(&format!("{}{}", value.name, comma));
            }
        }
        
        self.indent_level -= 1;
        self.write_line("}");
    }
    
    /// 生成结构体
    fn generate_struct(&mut self, struct_def: &Struct) {
        let export = if self.export { "export " } else { "" };
        
        self.write_line(&format!("{}interface {} {{", export, struct_def.name));
        self.indent_level += 1;
        
        for field in &struct_def.fields {
            self.generate_field(field);
        }
        
        self.indent_level -= 1;
        self.write_line("}");
    }
    
    /// 生成 Union (作为联合类型)
    fn generate_union(&mut self, union_def: &Union) {
        let export = if self.export { "export " } else { "" };
        
        // 先为每个字段生成一个接口
        for field in &union_def.fields {
            let ts_type = self.field_type_to_ts(&field.field_type);
            self.write_line(&format!(
                "{}interface {}_{} {{ {}: {} }}",
                export, union_def.name, field.name, field.name, ts_type
            ));
        }
        
        // 然后生成联合类型
        let union_types: Vec<String> = union_def
            .fields
            .iter()
            .map(|f| format!("{}_{}", union_def.name, f.name))
            .collect();
        
        self.write_line(&format!(
            "{}type {} = {};",
            export,
            union_def.name,
            union_types.join(" | ")
        ));
    }
    
    /// 生成异常
    fn generate_exception(&mut self, exception: &Exception) {
        let export = if self.export { "export " } else { "" };
        
        self.write_line(&format!("{}interface {} {{", export, exception.name));
        self.indent_level += 1;
        
        for field in &exception.fields {
            self.generate_field(field);
        }
        
        self.indent_level -= 1;
        self.write_line("}");
    }
    
    /// 生成服务接口
    fn generate_service(&mut self, service: &Service) {
        let export = if self.export { "export " } else { "" };
        
        let extends = if let Some(ref parent) = service.extends {
            format!(" extends {}", parent)
        } else {
            String::new()
        };
        
        self.write_line(&format!(
            "{}interface {}{} {{",
            export, service.name, extends
        ));
        self.indent_level += 1;
        
        for method in &service.methods {
            self.generate_method(method);
        }
        
        self.indent_level -= 1;
        self.write_line("}");
    }
    
    /// 生成服务方法
    fn generate_method(&mut self, method: &Method) {
        let params: Vec<String> = method
            .arguments
            .iter()
            .map(|arg| {
                let optional = if arg.requiredness == Requiredness::Optional {
                    "?"
                } else {
                    ""
                };
                let ts_type = self.field_type_to_ts(&arg.field_type);
                format!("{}{}: {}", arg.name, optional, ts_type)
            })
            .collect();
        
        let return_type = self.field_type_to_ts(&method.return_type);
        
        self.write_line(&format!(
            "{}({}): Promise<{}>;",
            method.name,
            params.join(", "),
            return_type
        ));
    }
    
    /// 生成字段
    fn generate_field(&mut self, field: &Field) {
        let readonly = if self.readonly { "readonly " } else { "" };
        let optional = if field.requiredness == Requiredness::Optional {
            "?"
        } else {
            ""
        };
        let ts_type = self.field_type_to_ts(&field.field_type);
        
        self.write_line(&format!(
            "{}{}{}: {};",
            readonly, field.name, optional, ts_type
        ));
    }
    
    /// 将 Thrift 类型转换为 TypeScript 类型
    fn field_type_to_ts(&self, field_type: &FieldType) -> String {
        match field_type {
            FieldType::Bool => "boolean".to_string(),
            FieldType::Byte | FieldType::I16 | FieldType::I32 => "number".to_string(),
            FieldType::I64 => "bigint".to_string(),
            FieldType::Double => "number".to_string(),
            FieldType::String => "string".to_string(),
            FieldType::Binary => "Uint8Array".to_string(),
            FieldType::Void => "void".to_string(),
            FieldType::List(inner) => {
                let inner_type = self.field_type_to_ts(inner);
                format!("{}[]", inner_type)
            }
            FieldType::Set(inner) => {
                let inner_type = self.field_type_to_ts(inner);
                format!("Set<{}>", inner_type)
            }
            FieldType::Map(key, value) => {
                let key_type = self.field_type_to_ts(key);
                let value_type = self.field_type_to_ts(value);
                format!("Map<{}, {}>", key_type, value_type)
            }
            FieldType::Custom(name) => name.clone(),
        }
    }
    
    /// 将常量值转换为 TypeScript 表达式
    fn const_value_to_ts(&self, value: &ConstValue) -> String {
        match value {
            ConstValue::Bool(b) => b.to_string(),
            ConstValue::Int(n) => n.to_string(),
            ConstValue::Double(n) => n.to_string(),
            ConstValue::String(s) => format!("\"{}\"", s.replace('\"', "\\\"")),
            ConstValue::Identifier(s) => s.clone(),
            ConstValue::List(items) => {
                let items_str: Vec<String> = items
                    .iter()
                    .map(|item| self.const_value_to_ts(item))
                    .collect();
                format!("[{}]", items_str.join(", "))
            }
            ConstValue::Map(items) => {
                let items_str: Vec<String> = items
                    .iter()
                    .map(|(k, v)| {
                        format!(
                            "[{}, {}]",
                            self.const_value_to_ts(k),
                            self.const_value_to_ts(v)
                        )
                    })
                    .collect();
                format!("new Map([{}])", items_str.join(", "))
            }
        }
    }
}

impl Default for TypeScriptGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_generate_struct() {
        let mut doc = ThriftDocument::new();
        doc.structs.push(Struct {
            name: "User".to_string(),
            fields: vec![
                Field {
                    id: Some(1),
                    requiredness: Requiredness::Required,
                    field_type: FieldType::I64,
                    name: "id".to_string(),
                    default_value: None,
                },
                Field {
                    id: Some(2),
                    requiredness: Requiredness::Required,
                    field_type: FieldType::String,
                    name: "name".to_string(),
                    default_value: None,
                },
            ],
        });
        
        let mut gen = TypeScriptGenerator::new();
        let output = gen.generate(&doc);
        
        assert!(output.contains("interface User"));
        assert!(output.contains("id: bigint"));
        assert!(output.contains("name: string"));
    }
    
    #[test]
    fn test_generate_enum() {
        let mut doc = ThriftDocument::new();
        doc.enums.push(Enum {
            name: "Status".to_string(),
            values: vec![
                EnumValue {
                    name: "ACTIVE".to_string(),
                    value: Some(1),
                },
                EnumValue {
                    name: "INACTIVE".to_string(),
                    value: Some(2),
                },
            ],
        });
        
        let mut gen = TypeScriptGenerator::new();
        let output = gen.generate(&doc);
        
        assert!(output.contains("enum Status"));
        assert!(output.contains("ACTIVE = 1"));
        assert!(output.contains("INACTIVE = 2"));
    }
}
