// Generated by thrift-ts-gen. DO NOT EDIT.
// Source: Thrift IDL

export type UserId = string;

export enum Status {
  ACTIVE = 1,
  INACTIVE = 2,
  UNKNOWN = 3,
}

export interface User {
  id: UserId;
  name?: string;
  age?: number;
  tags?: Array<string>;
  meta?: Record<string, string>;
}

export type LookupKey =
  | { kind: "user_id"; user_id: UserId }
  | { kind: "username"; username: string }
;

export interface UserService {
  get_user(args: { id: UserId }): Promise<User>;
  delete_user(args: { id: UserId }): Promise<void>;
}

