// Type definitions
#include "common.idl"

module Example {
    typedef sequence<string> StringList;
    typedef long ErrorCode;
    
    struct Configuration {
        string name;
        long port;
        boolean enabled;
    };
    
    enum Status {
        IDLE,
        RUNNING,
        STOPPED,
        ERROR
    };
};
