// This file is auto-generated by thrift-to-ts
// Do not edit manually

export const MAX_PAGE_SIZE: number = 100;

export const DEFAULT_LANGUAGE: string = "en";

export const SUPPORTED_LANGUAGES: string[] = ["en", "zh", "ja", "ko"];

export type Timestamp = bigint;

export type UUID = string;

export type Metadata = Map<string, string>;

export enum ErrorCode {
  OK = 0,
  UNKNOWN = 1,
  INVALID_ARGUMENT = 2,
  NOT_FOUND = 3,
  ALREADY_EXISTS = 4,
  PERMISSION_DENIED = 5,
  UNAUTHENTICATED = 6,
  INTERNAL = 7,
  UNAVAILABLE = 8,
  TIMEOUT = 9
}

export interface ResponseStatus {
  code: ErrorCode;
  message?: string;
  details?: Metadata;
}

export interface PageRequest {
  page: number;
  size: number;
  sortBy?: string;
  ascending?: boolean;
}

export interface PageInfo {
  currentPage: number;
  pageSize: number;
  totalItems: bigint;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
}

export interface KeyValue {
  key: string;
  value: string;
}

export interface TimeRange {
  start?: Timestamp;
  end?: Timestamp;
}

export interface GeoPoint {
  latitude: number;
  longitude: number;
}

export interface Money {
  currency: string;
  amount: bigint;
}

export interface FileInfo {
  id: UUID;
  name: string;
  mimeType: string;
  size: bigint;
  url: string;
  createdAt: Timestamp;
}

export interface ServiceException {
  code: ErrorCode;
  message: string;
  details?: Metadata;
}
