// This file is auto-generated by thrift-to-ts
// Do not edit manually

export enum UserStatus {
  ACTIVE = 1,
  INACTIVE = 2,
  SUSPENDED = 3,
  DELETED = 4
}

export enum Gender {
  UNKNOWN = 0,
  MALE = 1,
  FEMALE = 2
}

export interface Address {
  country: string;
  city: string;
  street?: string;
  zipCode?: string;
}

export interface UserProfile {
  avatar?: string;
  bio?: string;
  interests?: string[];
  socialLinks?: Map<string, string>;
}

export interface User {
  id: bigint;
  username: string;
  email: string;
  phone?: string;
  status: UserStatus;
  gender?: Gender;
  address?: Address;
  profile?: UserProfile;
  createdAt: bigint;
  updatedAt?: bigint;
}

export interface CreateUserRequest {
  username: string;
  email: string;
  phone?: string;
  gender?: Gender;
  address?: Address;
}

export interface CreateUserResponse {
  user: User;
  token: string;
}

export interface UpdateUserRequest {
  id: bigint;
  email?: string;
  phone?: string;
  gender?: Gender;
  address?: Address;
  profile?: UserProfile;
}

export interface Pagination {
  page: number;
  pageSize: number;
}

export interface UserListResponse {
  users: User[];
  total: number;
  page: number;
  pageSize: number;
}

export interface UserNotFoundException {
  userId: bigint;
  message: string;
}

export interface UserAlreadyExistsException {
  email: string;
  message: string;
}

export interface UserService {
  getUser(id: bigint): Promise<User>;
  listUsers(pagination: Pagination): Promise<UserListResponse>;
  createUser(request: CreateUserRequest): Promise<CreateUserResponse>;
  updateUser(request: UpdateUserRequest): Promise<User>;
  deleteUser(id: bigint): Promise<void>;
  searchUsers(keyword: string, pagination: Pagination): Promise<UserListResponse>;
}
