//! Hertz HTTP server code generator

use anyhow::Result;
use std::fs;
use std::path::Path;
use tracing::info;

use crate::parser::{ParsedFile, ParsedProject, ServiceDef};

use super::Generator;

/// Hertz code generator
pub struct HertzGenerator {
    /// Module name for the generated code
    module_name: String,
}

impl HertzGenerator {
    /// Create a new Hertz generator
    pub fn new(module_name: &str) -> Self {
        Self {
            module_name: module_name.to_string(),
        }
    }

    /// Generate model structs
    fn generate_models(&self, project: &ParsedProject, output_dir: &Path) -> Result<()> {
        let model_dir = output_dir.join("biz").join("model");
        fs::create_dir_all(&model_dir)?;

        for file in &project.files {
            if file.structs.is_empty() && file.enums.is_empty() {
                continue;
            }

            let file_name = file
                .file_path
                .file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_else(|| "model".to_string());

            let content = self.render_model(file);

            let output_path = model_dir.join(format!("{}.go", file_name));
            fs::write(&output_path, content)?;
            info!("Generated: {:?}", output_path);
        }

        Ok(())
    }

    fn render_model(&self, file: &ParsedFile) -> String {
        let mut content = String::new();
        
        content.push_str("// Code generated by thrift-proto-hertz-gen. DO NOT EDIT.\n");
        content.push_str("package model\n\n");
        content.push_str("// Placeholder is used to ensure this package is imported\n");
        content.push_str("var Placeholder = struct{}{}\n\n");

        // Render enums
        for enum_def in &file.enums {
            content.push_str(&format!("// {} enum type\n", enum_def.name));
            content.push_str(&format!("type {} int32\n\n", enum_def.name));
            content.push_str("const (\n");
            for (i, value) in enum_def.values.iter().enumerate() {
                let val = value.value.unwrap_or(i as i32);
                content.push_str(&format!("\t{}_{} {} = {}\n", enum_def.name, value.name, enum_def.name, val));
            }
            content.push_str(")\n\n");
        }

        // Render structs
        for struct_def in &file.structs {
            content.push_str(&format!("// {} struct\n", struct_def.name));
            content.push_str(&format!("type {} struct {{\n", struct_def.name));
            for field in &struct_def.fields {
                let json_tag = if field.optional {
                    format!("{},omitempty", to_snake_case(&field.name))
                } else {
                    to_snake_case(&field.name)
                };
                content.push_str(&format!(
                    "\t{} {} `json:\"{}\"`\n",
                    to_pascal_case(&field.name),
                    field.field_type.to_go_type(),
                    json_tag
                ));
            }
            content.push_str("}\n\n");
        }

        content
    }

    /// Generate handler functions
    fn generate_handlers(&self, project: &ParsedProject, output_dir: &Path) -> Result<()> {
        let handler_dir = output_dir.join("biz").join("handler");
        fs::create_dir_all(&handler_dir)?;

        for service in project.all_services() {
            let content = self.render_handler(service);

            let output_path = handler_dir.join(format!("{}.go", to_snake_case(&service.name)));
            fs::write(&output_path, content)?;
            info!("Generated: {:?}", output_path);
        }

        Ok(())
    }

    fn render_handler(&self, service: &ServiceDef) -> String {
        let mut content = String::new();
        
        content.push_str("// Code generated by thrift-proto-hertz-gen. DO NOT EDIT.\n");
        content.push_str("package handler\n\n");
        content.push_str("import (\n");
        content.push_str("\t\"context\"\n");
        content.push_str("\t\"github.com/cloudwego/hertz/pkg/app\"\n");
        content.push_str("\t\"github.com/cloudwego/hertz/pkg/common/utils\"\n");
        content.push_str("\t\"github.com/cloudwego/hertz/pkg/protocol/consts\"\n");
        content.push_str(&format!("\t\"{}/biz/model\"\n", self.module_name));
        content.push_str(")\n\n");
        content.push_str("// Ensure model package is imported (remove if not needed)\n");
        content.push_str("var _ = model.Placeholder\n\n");

        for method in &service.methods {
            let handler_name = format!("{}Handler", to_pascal_case(&method.name));
            
            content.push_str(&format!("// {} handles {} requests\n", handler_name, method.name));
            if let Some(endpoint) = &method.http_endpoint {
                content.push_str(&format!("// {} {}\n", endpoint.method.as_str(), endpoint.path));
            }
            content.push_str(&format!("func {}(ctx context.Context, c *app.RequestContext) {{\n", handler_name));
            content.push_str("\t// TODO: Implement logic\n");
            content.push_str("\t\n");
            content.push_str("\t// Example request binding\n");
            content.push_str("\t// var req model.RequestType\n");
            content.push_str("\t// if err := c.BindAndValidate(&req); err != nil {\n");
            content.push_str("\t// \tc.JSON(consts.StatusBadRequest, utils.H{\"error\": err.Error()})\n");
            content.push_str("\t// \treturn\n");
            content.push_str("\t// }\n");
            content.push_str("\n");
            content.push_str("\tc.JSON(consts.StatusOK, utils.H{\n");
            content.push_str(&format!("\t\t\"message\": \"{} handler not implemented\",\n", method.name));
            content.push_str("\t})\n");
            content.push_str("}\n\n");
        }

        content
    }

    /// Generate router configuration
    fn generate_router(&self, project: &ParsedProject, output_dir: &Path) -> Result<()> {
        let router_dir = output_dir.join("biz").join("router");
        fs::create_dir_all(&router_dir)?;

        let content = self.render_router(project);

        let output_path = router_dir.join("router.go");
        fs::write(&output_path, content)?;
        info!("Generated: {:?}", output_path);

        Ok(())
    }

    fn render_router(&self, project: &ParsedProject) -> String {
        let mut content = String::new();
        
        content.push_str("// Code generated by thrift-proto-hertz-gen. DO NOT EDIT.\n");
        content.push_str("package router\n\n");
        content.push_str("import (\n");
        content.push_str("\t\"github.com/cloudwego/hertz/pkg/app/server\"\n");
        content.push_str(&format!("\t\"{}/biz/handler\"\n", self.module_name));
        content.push_str(")\n\n");
        content.push_str("// Register registers all routes\n");
        content.push_str("func Register(h *server.Hertz) {\n");

        for service in project.all_services() {
            for method in &service.methods {
                if let Some(endpoint) = &method.http_endpoint {
                    let handler_name = format!("{}Handler", to_pascal_case(&method.name));
                    let http_method = endpoint.method.as_str();
                    content.push_str(&format!(
                        "\th.{}(\"{}\", handler.{})\n",
                        http_method, endpoint.path, handler_name
                    ));
                }
            }
        }

        content.push_str("}\n");

        content
    }

    /// Generate main.go
    fn generate_main(&self, _project: &ParsedProject, output_dir: &Path) -> Result<()> {
        let content = format!(
            r#"// Code generated by thrift-proto-hertz-gen. DO NOT EDIT.
package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"{}/biz/router"
)

func main() {{
	h := server.Default(server.WithHostPorts(":8888"))

	router.Register(h)

	h.Spin()
}}
"#,
            self.module_name
        );

        let output_path = output_dir.join("main.go");
        fs::write(&output_path, content)?;
        info!("Generated: {:?}", output_path);

        Ok(())
    }

    /// Generate go.mod file
    fn generate_go_mod(&self, output_dir: &Path) -> Result<()> {
        let content = format!(
            r#"module {}

go 1.21

require (
	github.com/cloudwego/hertz v0.7.3
)
"#,
            self.module_name
        );

        let output_path = output_dir.join("go.mod");
        fs::write(&output_path, content)?;
        info!("Generated: {:?}", output_path);

        Ok(())
    }
}

impl Generator for HertzGenerator {
    fn generate(&self, project: &ParsedProject, output_dir: &Path) -> Result<()> {
        info!("Generating Hertz HTTP server to: {:?}", output_dir);

        // Create output directory
        fs::create_dir_all(output_dir)?;

        // Generate all components
        self.generate_go_mod(output_dir)?;
        self.generate_main(project, output_dir)?;
        self.generate_models(project, output_dir)?;
        self.generate_handlers(project, output_dir)?;
        self.generate_router(project, output_dir)?;

        info!("Code generation completed successfully");
        Ok(())
    }
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Convert string to snake_case
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

/// Convert string to PascalCase
fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    
    for c in s.chars() {
        if c == '_' || c == '-' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_uppercase().next().unwrap());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("UserService"), "user_service");
        assert_eq!(to_snake_case("GetUser"), "get_user");
        assert_eq!(to_snake_case("ID"), "i_d");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("user_service"), "UserService");
        assert_eq!(to_pascal_case("get_user"), "GetUser");
    }
}
