use std::fs;
use std::path::PathBuf;

use anyhow::{anyhow, Context, Result};
use clap::{Parser as ClapParser, ValueEnum};
use thrift_parser::document::Document;
use thrift_parser::types::FieldType;
use thrift_parser::Parser as ThriftParser;

#[derive(Debug, Copy, Clone, ValueEnum)]
enum I64Mode {
    /// Map i64 -> string (safe for JSON; no precision loss).
    String,
    /// Map i64 -> bigint (requires consumers to support bigint).
    Bigint,
}

#[derive(Debug, ClapParser)]
#[command(name = "thrift-ts-gen", version)]
#[command(about = "Parse Thrift IDL and generate TypeScript types", long_about = None)]
struct Args {
    /// Input thrift file path.
    #[arg(short, long)]
    input: PathBuf,

    /// Output TypeScript file path (defaults to stdout).
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// Wrap output in `export namespace <name> { ... }`.
    #[arg(long)]
    wrap_namespace: bool,

    /// Namespace name for wrapping (defaults to the `namespace js ...` in thrift if present).
    #[arg(long)]
    namespace: Option<String>,

    /// Mapping for Thrift `i64`.
    #[arg(long, value_enum, default_value_t = I64Mode::String)]
    i64: I64Mode,
}

fn main() -> Result<()> {
    let args = Args::parse();
    let idl = fs::read_to_string(&args.input)
        .with_context(|| format!("failed to read {}", args.input.display()))?;
    let (remains, doc) =
        Document::parse(&idl).map_err(|e| anyhow!("thrift parse error: {e:?}"))?;
    if !remains.trim().is_empty() {
        return Err(anyhow!(
            "thrift parse did not consume all input; remains: {:?}",
            remains
        ));
    }

    let ts = generate_typescript(&doc, &args);
    match args.output {
        Some(path) => {
            fs::write(&path, ts).with_context(|| format!("failed to write {}", path.display()))?;
        }
        None => {
            print!("{ts}");
        }
    }
    Ok(())
}

fn generate_typescript(doc: &Document, args: &Args) -> String {
    let mut out = String::new();
    out.push_str("// Generated by thrift-ts-gen. DO NOT EDIT.\n");
    out.push_str("// Source: Thrift IDL\n\n");

    let ns = args.namespace.clone().or_else(|| {
        doc.namespaces
            .iter()
            .find(|n| n.scope.as_str() == "js")
            .map(|n| n.name.to_string())
    });

    if args.wrap_namespace {
        let ns = ns.unwrap_or_else(|| "thrift".to_string());
        out.push_str(&format!("export namespace {ns} {{\n"));
        out.push_str(&indent(&emit_document(doc, args), 2));
        out.push_str("}\n");
        return out;
    }

    out.push_str(&emit_document(doc, args));
    out
}

fn emit_document(doc: &Document, args: &Args) -> String {
    let mut out = String::new();

    for td in &doc.typedefs {
        let alias = td.alias.as_str();
        let ty = to_ts_type(&td.old, args);
        out.push_str(&format!("export type {alias} = {ty};\n"));
    }
    if !doc.typedefs.is_empty() {
        out.push('\n');
    }

    for en in &doc.enums {
        out.push_str(&emit_enum(en.name.as_ref(), &en.children));
        out.push('\n');
    }

    for st in &doc.structs {
        out.push_str(&emit_struct_like("interface", st.name.as_ref(), &st.fields, args));
        out.push('\n');
    }

    for ex in &doc.exceptions {
        out.push_str(&emit_struct_like("interface", ex.name.as_ref(), &ex.fields, args));
        out.push('\n');
    }

    for un in &doc.unions {
        out.push_str(&emit_union(un.name.as_ref(), &un.fields, args));
        out.push('\n');
    }

    for svc in &doc.services {
        out.push_str(&emit_service(svc.name.as_ref(), &svc.functions, args));
        out.push('\n');
    }

    out
}

fn emit_enum(name: &str, values: &[thrift_parser::definition::EnumValue]) -> String {
    let mut out = String::new();
    out.push_str(&format!("export enum {name} {{\n"));

    let mut next: i64 = 0;
    for v in values {
        let vn = v.name.as_str();
        let val = v
            .value
            .map(|x| x.into_inner())
            .unwrap_or_else(|| next);
        next = val.saturating_add(1);
        out.push_str(&format!("  {vn} = {val},\n"));
    }

    out.push_str("}\n");
    out
}

fn emit_struct_like(kind: &str, name: &str, fields: &[thrift_parser::field::Field], args: &Args) -> String {
    let mut out = String::new();
    out.push_str(&format!("export {kind} {name} {{\n"));
    for f in fields {
        let fname = f.name.as_str();
        let ty = to_ts_type(&f.type_, args);
        let optional = f.required != Some(true);
        if optional {
            out.push_str(&format!("  {fname}?: {ty};\n"));
        } else {
            out.push_str(&format!("  {fname}: {ty};\n"));
        }
    }
    out.push_str("}\n");
    out
}

fn emit_union(name: &str, fields: &[thrift_parser::field::Field], args: &Args) -> String {
    let mut out = String::new();
    out.push_str(&format!("export type {name} =\n"));
    for f in fields {
        let fname = f.name.as_str();
        let ty = to_ts_type(&f.type_, args);
        out.push_str(&format!("  | {{ kind: \"{fname}\"; {fname}: {ty} }}\n"));
    }
    out.push_str(";\n");
    out
}

fn emit_service(name: &str, fns: &[thrift_parser::functions::Function], args: &Args) -> String {
    let mut out = String::new();
    out.push_str(&format!("export interface {name} {{\n"));
    for f in fns {
        let fn_name = f.name.as_str();
        let ret = match &f.returns {
            Some(t) => to_ts_type(t, args),
            None => "void".to_string(),
        };

        if f.parameters.is_empty() {
            out.push_str(&format!("  {fn_name}(): Promise<{ret}>;\n"));
            continue;
        }

        out.push_str(&format!("  {fn_name}(args: {{ "));
        for (i, p) in f.parameters.iter().enumerate() {
            let pname = p.name.as_str();
            let pty = to_ts_type(&p.type_, args);
            let optional = p.required != Some(true);
            if i != 0 {
                out.push_str("; ");
            }
            if optional {
                out.push_str(&format!("{pname}?: {pty}"));
            } else {
                out.push_str(&format!("{pname}: {pty}"));
            }
        }
        out.push_str(&format!(" }}): Promise<{ret}>;\n"));
    }
    out.push_str("}\n");
    out
}

fn to_ts_type(t: &FieldType, args: &Args) -> String {
    match t {
        FieldType::Bool => "boolean".to_string(),
        FieldType::Byte | FieldType::I8 | FieldType::I16 | FieldType::I32 | FieldType::Double => {
            "number".to_string()
        }
        FieldType::I64 => match args.i64 {
            I64Mode::String => "string".to_string(),
            I64Mode::Bigint => "bigint".to_string(),
        },
        FieldType::String => "string".to_string(),
        FieldType::Binary => "Uint8Array".to_string(),
        FieldType::List(v) | FieldType::Set(v) => format!("Array<{}>", to_ts_type(v.as_ref(), args)),
        FieldType::Map(k, v) => {
            let kt = to_ts_type(k.as_ref(), args);
            let vt = to_ts_type(v.as_ref(), args);
            // If key is string/number, prefer Record; otherwise fall back to Map.
            if kt == "string" || kt == "number" {
                format!("Record<{kt}, {vt}>")
            } else {
                format!("Map<{kt}, {vt}>")
            }
        }
        FieldType::Identifier(id) => id.to_string(),
    }
}

fn indent(s: &str, n: usize) -> String {
    let pad = " ".repeat(n);
    s.lines()
        .map(|l| {
            if l.is_empty() {
                "\n".to_string()
            } else {
                format!("{pad}{l}\n")
            }
        })
        .collect()
}

